# Generated by Django 5.0.1 on 2024-01-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLogReturn',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('condition_when_returned', models.CharField(blank=True, max_length=255, null=True)),
                ('return_status', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.employee')),
            ],
            options={
                'verbose_name': 'Devicelogreturn',
                'verbose_name_plural': 'Devicelogreturns',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('check_out_time', models.DateTimeField()),
                ('condition_when_out', models.CharField(max_length=255)),
                ('return_status', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.employee')),
            ],
            options={
                'verbose_name': 'Devicelog',
                'verbose_name_plural': 'Devicelogs',
                'ordering': ['id'],
            },
        ),
    ]
